export const all_ues = [
    {
        "Formation": "Licence",
        "Semestre": 1,
        "Ref": "UEinfo1.1",
        "Intitule": "METHODOLOGIE S1 (UE TRANSVERSALE)",
        "Statut": "obligatoire",
        "h_CM": 2,
        "h_TD": 7,
        "h_TP": 0,
        "Effectif": "",
        "grCM": 2,
        "grTD": 4,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 1,
        "Ref": "UEinfo1.3",
        "Intitule": "BASES DE PROGRAMMATION",
        "Statut": "obligatoire",
        "h_CM": 12,
        "h_TD": 24,
        "h_TP": 12,
        "Effectif": 301,
        "grCM": 1,
        "grTD": 8,
        "grTP": 19
    },
    {
        "Formation": "Licence",
        "Semestre": 1,
        "Ref": "UEinfo1.4",
        "Intitule": "EXPERIENCES INFORMATIQUES",
        "Statut": "obligatoire",
        "h_CM": 3,
        "h_TD": 0,
        "h_TP": 18,
        "Effectif": 277,
        "grCM": 1,
        "grTD": 0,
        "grTP": 17
    },
    {
        "Formation": "Licence",
        "Semestre": 1,
        "Ref": "UEinfo1.5",
        "Intitule": "INTERNET ET WEB",
        "Statut": "obligatoire",
        "h_CM": 9,
        "h_TD": 18,
        "h_TP": 0,
        "Effectif": 294,
        "grCM": 1,
        "grTD": 10,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 2,
        "Ref": "UEinfo2.1",
        "Intitule": "METHODOLOGIE S2 (UE TRANSVERSALE)",
        "Statut": "obligatoire",
        "h_CM": 0,
        "h_TD": 6,
        "h_TP": 0,
        "Effectif": "",
        "grCM": 0,
        "grTD": 7,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 2,
        "Ref": "UEinfo2.3",
        "Intitule": "ALGORITHMIQUE ET PROGRAMMATION",
        "Statut": "obligatoire",
        "h_CM": 8,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 302,
        "grCM": 1,
        "grTD": 7,
        "grTP": 14
    },
    {
        "Formation": "Licence",
        "Semestre": 2,
        "Ref": "UEinfo2.4",
        "Intitule": "ARCHITECTURE DES ORDINATEURS, REPRESENTATION DE L'INFORMATION",
        "Statut": "obligatoire",
        "h_CM": 12,
        "h_TD": 16,
        "h_TP": 0,
        "Effectif": 305,
        "grCM": 1,
        "grTD": 7,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 2,
        "Ref": "UEinfo2.5",
        "Intitule": "INITIATION AUX BASES DE DONNEES",
        "Statut": "obligatoire",
        "h_CM": 8,
        "h_TD": 20,
        "h_TP": 0,
        "Effectif": 297,
        "grCM": 1,
        "grTD": 7,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 2,
        "Ref": "UEinfo2.6",
        "Intitule": "ELEMENTS DE LOGIQUE FORMELLE ET DU RAISONNEMENT MATHEMATIQUE",
        "Statut": "obligatoire",
        "h_CM": 12,
        "h_TD": 16,
        "h_TP": 0,
        "Effectif": 238,
        "grCM": 1,
        "grTD": 6,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 2,
        "Ref": "UEinfo2.7",
        "Intitule": "SCILAB _ MATLAB",
        "Statut": "obligatoire",
        "h_CM": 9,
        "h_TD": 9,
        "h_TP": 12,
        "Effectif": 130,
        "grCM": 0,
        "grTD": "?",
        "grTP": "?"
    },
    {
        "Formation": "Licence",
        "Semestre": 3,
        "Ref": "UEinfo3.1",
        "Intitule": "METHODOLOGIE S3 (UE TRANSVERSALE)",
        "Statut": "obligatoire",
        "h_CM": "",
        "h_TD": 14,
        "h_TP": 0,
        "Effectif": "",
        "grCM": 0,
        "grTD": 4,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 3,
        "Ref": "UEinfo3.2",
        "Intitule": "STRUCTURES DE DONNEES FONDAMENTALES",
        "Statut": "obligatoire",
        "h_CM": 26,
        "h_TD": 34,
        "h_TP": 10,
        "Effectif": 139,
        "grCM": 1,
        "grTD": 4,
        "grTP": 8
    },
    {
        "Formation": "Licence",
        "Semestre": 3,
        "Ref": "UEinfo3.3",
        "Intitule": "BASES DE DONNEES RELATIONNELLES",
        "Statut": "obligatoire",
        "h_CM": 16,
        "h_TD": 24,
        "h_TP": 20,
        "Effectif": 141,
        "grCM": 1,
        "grTD": 4,
        "grTP": 8
    },
    {
        "Formation": "Licence",
        "Semestre": 3,
        "Ref": "UEinfo3.4",
        "Intitule": "PROGRAMMATION ET LANGAGE C",
        "Statut": "obligatoire",
        "h_CM": 18,
        "h_TD": 18,
        "h_TP": 24,
        "Effectif": 129,
        "grCM": 1,
        "grTD": 4,
        "grTP": 8
    },
    {
        "Formation": "Licence",
        "Semestre": 3,
        "Ref": "UEinfo3.5",
        "Intitule": "ARCHITECTURE DES ORDINATEURS, LANGAGE D'ASSEMBLAGE",
        "Statut": "optionnelle",
        "h_CM": 6,
        "h_TD": 12,
        "h_TP": 12,
        "Effectif": 103,
        "grCM": 1,
        "grTD": 3,
        "grTP": 6
    },
    {
        "Formation": "Licence",
        "Semestre": 3,
        "Ref": "UEinfo3.6",
        "Intitule": "PROGRAMMATION FONCTIONNELLE",
        "Statut": "optionnelle",
        "h_CM": 8,
        "h_TD": 12,
        "h_TP": 10,
        "Effectif": 99,
        "grCM": 1,
        "grTD": 3,
        "grTP": 6
    },
    {
        "Formation": "Licence",
        "Semestre": 3,
        "Ref": "UEinfo3.7",
        "Intitule": "BASES DE GESTION: ORGANISATION DE L'ENTREPRISE ET FONCTION COMMERCIALE",
        "Statut": "optionnelle",
        "h_CM": 10,
        "h_TD": 20,
        "h_TP": 0,
        "Effectif": 67,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 4,
        "Ref": "UEinfo4.1",
        "Intitule": "METHODOLOGIE S4 (UE TRANSVERSALES)",
        "Statut": "obligatoire",
        "h_CM": "",
        "h_TD": 14,
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": 4,
        "grTP": ""
    },
    {
        "Formation": "Licence",
        "Semestre": 4,
        "Ref": "UEinfo4.1",
        "Intitule": "CYCLE DE CONFERENCES SCIENTIFIQUES",
        "Statut": "obligatoire",
        "h_CM": "",
        "h_TD": "",
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": "",
        "grTP": ""
    },
    {
        "Formation": "Licence",
        "Semestre": 4,
        "Ref": "UEinfo4.2",
        "Intitule": "ALGORITHMIQUE DES GRAPHES",
        "Statut": "obligatoire",
        "h_CM": 22,
        "h_TD": 30,
        "h_TP": 8,
        "Effectif": 139,
        "grCM": 1,
        "grTD": 4,
        "grTP": 8
    },
    {
        "Formation": "Licence",
        "Semestre": 4,
        "Ref": "UEinfo4.3",
        "Intitule": "PROGRAMMATION OBJET 1",
        "Statut": "obligatoire",
        "h_CM": 16,
        "h_TD": 26,
        "h_TP": 18,
        "Effectif": 136,
        "grCM": 1,
        "grTD": 4,
        "grTP": 8
    },
    {
        "Formation": "Licence",
        "Semestre": 4,
        "Ref": "UEinfo4.4",
        "Intitule": "SYSTEME D'EXPLOITATION",
        "Statut": "obligatoire",
        "h_CM": 16,
        "h_TD": 16,
        "h_TP": 28,
        "Effectif": 136,
        "grCM": 1,
        "grTD": 4,
        "grTP": 8
    },
    {
        "Formation": "Licence",
        "Semestre": 4,
        "Ref": "UEinfo4.5",
        "Intitule": "PROGRAMMATION WEB",
        "Statut": "optionnelle",
        "h_CM": 10,
        "h_TD": 0,
        "h_TP": 20,
        "Effectif": 125,
        "grCM": 1,
        "grTD": 0,
        "grTP": 8
    },
    {
        "Formation": "Licence",
        "Semestre": 4,
        "Ref": "UEinfo4.6",
        "Intitule": "ALGORITHMIQUE AVANCE",
        "Statut": "optionnelle",
        "h_CM": 8,
        "h_TD": 14,
        "h_TP": 8,
        "Effectif": 76,
        "grCM": 1,
        "grTD": 2,
        "grTP": 4
    },
    {
        "Formation": "Licence",
        "Semestre": 4,
        "Ref": "UEinfo4.7",
        "Intitule": "SYSTEME D'INFORMATION COMPTABLE",
        "Statut": "optionnelle",
        "h_CM": 10,
        "h_TD": 20,
        "h_TP": 0,
        "Effectif": 58,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.01",
        "Intitule": "PREPARATION A L'INSERTION PROFESSIONNELLE (UE TRANSVERSALE)",
        "Statut": "obligatoire",
        "h_CM": 0,
        "h_TD": 14,
        "h_TP": 0,
        "Effectif": "",
        "grCM": 0,
        "grTD": 2,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.2",
        "Intitule": "LANGAGES FORMELS",
        "Statut": "obligatoire",
        "h_CM": 10,
        "h_TD": 20,
        "h_TP": 0,
        "Effectif": 65,
        "grCM": 1,
        "grTD": 3,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.3",
        "Intitule": "THEORIE DU SYSTEME 1",
        "Statut": "obligatoire",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 64,
        "grCM": 1,
        "grTD": 3,
        "grTP": 6
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.4",
        "Intitule": "THEORIE DU SYSTEME 2",
        "Statut": "obligatoire parcours Info",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 65,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.5",
        "Intitule": "MODELISATION OBJET",
        "Statut": "obligatoire parcours MIAGE\noptionnelle parcours Info",
        "h_CM": 8,
        "h_TD": 12,
        "h_TP": 10,
        "Effectif": 61,
        "grCM": 1,
        "grTD": 3,
        "grTP": 6
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.6",
        "Intitule": "PROGRAMMATION OBJET 2",
        "Statut": "obligatoire parcours MIAGE\noptionnelle parcours Info",
        "h_CM": 4,
        "h_TD": 26,
        "h_TP": 0,
        "Effectif": 63,
        "grCM": 1,
        "grTD": 3,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.7",
        "Intitule": "METHODE D'ANALYSE ET DE CONCEPTION DE SYSTEME D'INFORMATIONS",
        "Statut": "obligatoire parcours MIAGE\noptionnelle parcours Info",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": 0,
        "Effectif": 60,
        "grCM": 1,
        "grTD": 3,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.8",
        "Intitule": "FRAMEWORK WEB",
        "Statut": "optionnelle",
        "h_CM": 4,
        "h_TD": 0,
        "h_TP": 26,
        "Effectif": 61,
        "grCM": 1,
        "grTD": 0,
        "grTP": 6
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.9",
        "Intitule": "METHODES FORMELLES D'AIDE A LA DETECTION D'ERREURS",
        "Statut": "optionnelle",
        "h_CM": 12,
        "h_TD": 18,
        "h_TP": 0,
        "Effectif": 13,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.10",
        "Intitule": "PROGRAMMATION DES SYSTEMES D'INFORMATIONS",
        "Statut": "obligatoire parcours Info",
        "h_CM": 10,
        "h_TD": 0,
        "h_TP": 20,
        "Effectif": 35,
        "grCM": 1,
        "grTD": 0,
        "grTP": 2
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.11",
        "Intitule": "SYSTEME D'INFORMATIONS FINANCIERES",
        "Statut": "obligatoire parcours MIAGE",
        "h_CM": 10,
        "h_TD": 20,
        "h_TP": 0,
        "Effectif": 35,
        "grCM": 1,
        "grTD": 2,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.12",
        "Intitule": "MATHEMATIQUES FINANCIERES",
        "Statut": "obligatoire parcours MIAGE",
        "h_CM": 12,
        "h_TD": 18,
        "h_TP": 0,
        "Effectif": 35,
        "grCM": 1,
        "grTD": 2,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo5.13",
        "Intitule": "COMPLEMENTS INFORMATIQUES",
        "Statut": "obligatoire parcours REL",
        "h_CM": 20,
        "h_TD": 40,
        "h_TP": 0,
        "Effectif": 0,
        "grCM": 0,
        "grTD": 0,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 5,
        "Ref": "UEinfo1.3",
        "Intitule": "BASES DE PROGRAMMATION - REL",
        "Statut": "obligatoire parcours REL",
        "h_CM": 12,
        "h_TD": 24,
        "h_TP": 12,
        "Effectif": 0,
        "grCM": 0,
        "grTD": 0,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 6,
        "Ref": "UEinfo6.1",
        "Intitule": "STAGE 8 SEMAINES",
        "Statut": "obligatoire",
        "h_CM": "",
        "h_TD": "",
        "h_TP": "",
        "Effectif": 70,
        "grCM": "",
        "grTD": "",
        "grTP": ""
    },
    {
        "Formation": "Licence",
        "Semestre": 6,
        "Ref": "UEinfo6.2",
        "Intitule": "RESEAU",
        "Statut": "obligatoire",
        "h_CM": 20,
        "h_TD": 22,
        "h_TP": 18,
        "Effectif": 118,
        "grCM": 1,
        "grTD": 3,
        "grTP": 6
    },
    {
        "Formation": "Licence",
        "Semestre": 6,
        "Ref": "UEinfo6.3",
        "Intitule": "PROJET",
        "Statut": "obligatoire",
        "h_CM": 6,
        "h_TD": 14,
        "h_TP": 40,
        "Effectif": 118,
        "grCM": 1,
        "grTD": 3,
        "grTP": 6
    },
    {
        "Formation": "Licence",
        "Semestre": 6,
        "Ref": "UEinfo6.4",
        "Intitule": "INTELLIGENCE ARTIFICIELLE",
        "Statut": "optionnelle",
        "h_CM": 8,
        "h_TD": 10,
        "h_TP": 12,
        "Effectif": 93,
        "grCM": 1,
        "grTD": 2,
        "grTP": 4
    },
    {
        "Formation": "Licence",
        "Semestre": 6,
        "Ref": "UEinfo6.5",
        "Intitule": "COMPILATION",
        "Statut": "optionnelle",
        "h_CM": 14,
        "h_TD": 16,
        "h_TP": 0,
        "Effectif": 51,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 6,
        "Ref": "UEinfo6.6",
        "Intitule": "METHODES QUANTITATIVES ET DECISION",
        "Statut": "optionnelle",
        "h_CM": 12,
        "h_TD": 14,
        "h_TP": 4,
        "Effectif": 35,
        "grCM": 1,
        "grTD": 2,
        "grTP": 4
    },
    {
        "Formation": "Licence",
        "Semestre": 6,
        "Ref": "UEinfo6.8",
        "Intitule": "XML",
        "Statut": "optionnelle",
        "h_CM": 10,
        "h_TD": 0,
        "h_TP": 20,
        "Effectif": 69,
        "grCM": 1,
        "grTD": 0,
        "grTP": 4
    },
    {
        "Formation": "Licence",
        "Semestre": 6,
        "Ref": "UEinfo6.9",
        "Intitule": "INITIATION A LA CRYPTOLOGIE ET AU CALCUL DISTRIBUE",
        "Statut": "optionnelle parcours Info",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": 0,
        "Effectif": 45,
        "grCM": 1,
        "grTD": 2,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": 6,
        "Ref": "UEinfo6.7",
        "Intitule": "SYSTEME D'INFORMATION POUR LA GESTION",
        "Statut": "obligatoire parcours MIAGE",
        "h_CM": 10,
        "h_TD": 20,
        "h_TP": 0,
        "Effectif": 35,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": "Foad",
        "Ref": "B211",
        "Intitule": "Programmation evenementielle et Interfaces Homme-Machine",
        "Statut": "",
        "h_CM": "",
        "h_TD": 10,
        "h_TP": "",
        "Effectif": "",
        "grCM": 1,
        "grTD": 2,
        "grTP": 0
    },
    {
        "Formation": "Licence",
        "Semestre": "Foad",
        "Ref": "B212",
        "Intitule": "Programmation orientee objet-Java",
        "Statut": "",
        "h_CM": "",
        "h_TD": 10,
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Licence",
        "Semestre": "Foad",
        "Ref": "B222",
        "Intitule": "Bases de telecommunications",
        "Statut": "",
        "h_CM": "",
        "h_TD": 10,
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Licence",
        "Semestre": "Foad",
        "Ref": "B104",
        "Intitule": "Graphes",
        "Statut": "",
        "h_CM": "",
        "h_TD": 10,
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,1",
        "Intitule": "Conduite de projet",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,2",
        "Intitule": "Programmation evenementielle",
        "Statut": "Obligatoire",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,3",
        "Intitule": "Administration des SE",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,4",
        "Intitule": "Decouverte de la recherche",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,5",
        "Intitule": "Cryptographie",
        "Statut": "Obligatoire",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,6",
        "Intitule": "Architecture des Systèmes d'Information",
        "Statut": "Optionnel",
        "h_CM": 0,
        "h_TD": 30,
        "h_TP": 0,
        "Effectif": 20,
        "grCM": 0,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,7",
        "Intitule": "Administration des parcs heterogènes",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,8",
        "Intitule": "Reseaux et communications",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,9",
        "Intitule": "Complexites",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": 7.1,
        "Intitule": "Systèmes distribues 1",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 1,
        "Ref": "7,11",
        "Intitule": "Initiation à la modelisation lineaire",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": "8,1",
        "Intitule": "BD et Big Data",
        "Statut": "Obligatoire",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": "8,2",
        "Intitule": "Projet de specialite",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 10,
        "h_TP": 20,
        "Effectif": 40,
        "grCM": "",
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": "8,3",
        "Intitule": "Seminaires",
        "Statut": "Obligatoire",
        "h_CM": 30,
        "h_TD": "",
        "h_TP": "",
        "Effectif": 40,
        "grCM": 1,
        "grTD": 0,
        "grTP": 0
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": "8,4",
        "Intitule": "Securisation des reseaux",
        "Statut": "Obligatoire",
        "h_CM": 12,
        "h_TD": "",
        "h_TP": 18,
        "Effectif": 40,
        "grCM": 1,
        "grTD": "",
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": "8,5",
        "Intitule": "Anglais",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 40,
        "h_TP": "",
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": "8,6",
        "Intitule": "Contrôle Qualite",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 18,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": "8,7",
        "Intitule": "Decouverte des laboratoires",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 17,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": "8,8",
        "Intitule": "Administration des systèmes d’exploitation 2",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 18,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": "8,9",
        "Intitule": "Services reseaux",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 18,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": 8.1,
        "Intitule": "Systèmes distribues avec fautes",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 18,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": 8.11,
        "Intitule": "Acquisition et traitement d'images",
        "Statut": "Optionnel",
        "h_CM": 16,
        "h_TD": 12,
        "h_TP": 12,
        "Effectif": 10,
        "grCM": 0,
        "grTD": 0,
        "grTP": 0
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": 8.12,
        "Intitule": "Architecture client_serveur",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": 8.13,
        "Intitule": "Risques et deontologie",
        "Statut": "Optionnel",
        "h_CM": 30,
        "h_TD": "",
        "h_TP": "",
        "Effectif": 10,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 2,
        "Ref": 8.14,
        "Intitule": "Projet Professionnel",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": "",
        "h_TP": "",
        "Effectif": 40,
        "grCM": "",
        "grTD": "",
        "grTP": ""
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.1,
        "Intitule": "Projet thematique 1",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": "",
        "h_TP": 30,
        "Effectif": 40,
        "grCM": "",
        "grTD": "",
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.2,
        "Intitule": "Optimisation et heuristiques pour les reseaux",
        "Statut": "Obligatoire",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.3,
        "Intitule": "Internet des objets",
        "Statut": "Obligatoire",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.4,
        "Intitule": "Anglais",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 40,
        "h_TP": "",
        "Effectif": 40,
        "grCM": 0,
        "grTD": 1,
        "grTP": 0
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.5,
        "Intitule": "Hebergement",
        "Statut": "Obligatoire",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 30,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.6,
        "Intitule": "Virtualisation",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 30,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.7,
        "Intitule": "Infrastructure des reseaux locaux et d'internet",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 30,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.8,
        "Intitule": "Architectures securisees",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 30,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.9,
        "Intitule": "Systèmes distribues 2",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 10,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.1,
        "Intitule": "Algorithmique mobile",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 10,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.11,
        "Intitule": "Localisation et navigation des robots",
        "Statut": "Optionnel",
        "h_CM": 16,
        "h_TD": 12,
        "h_TP": 12,
        "Effectif": 23,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 3,
        "Ref": 9.12,
        "Intitule": "Perception distribuee : fondements",
        "Statut": "Optionnel",
        "h_CM": 14,
        "h_TD": 13,
        "h_TP": 13,
        "Effectif": 10,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 4,
        "Ref": 10.1,
        "Intitule": "Projet thematique 2",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": "",
        "h_TP": 30,
        "Effectif": 40,
        "grCM": "",
        "grTD": "",
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 4,
        "Ref": 10.2,
        "Intitule": "Convergence et terminaux mobiles",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 30,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 4,
        "Ref": 10.3,
        "Intitule": "Marches professionnels et bilan de competences",
        "Statut": "Optionnel",
        "h_CM": 30,
        "h_TD": "",
        "h_TP": "",
        "Effectif": 30,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 4,
        "Ref": 10.4,
        "Intitule": "Infrastructures du calcul distribue",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 30,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 4,
        "Ref": 10.5,
        "Intitule": "Haute disponibilte",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 30,
        "grCM": 1,
        "grTD": 1,
        "grTP": 2
    },
    {
        "Formation": "Master Info",
        "Semestre": 4,
        "Ref": 10.6,
        "Intitule": "Projet Professionnel (annuel)",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": "",
        "h_TP": "",
        "Effectif": 30,
        "grCM": "",
        "grTD": "",
        "grTP": ""
    },
    {
        "Formation": "Master Info",
        "Semestre": 4,
        "Ref": 10.7,
        "Intitule": "Projet Professionnel",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": "",
        "h_TP": "",
        "Effectif": 10,
        "grCM": "",
        "grTD": "",
        "grTP": ""
    },
    {
        "Formation": "Master Info",
        "Semestre": 4,
        "Ref": 10.8,
        "Intitule": "Numerisation 3D grande echelle",
        "Statut": "Optionnel",
        "h_CM": 14,
        "h_TD": 13,
        "h_TP": 13,
        "Effectif": 10,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Info",
        "Semestre": 4,
        "Ref": 10.9,
        "Intitule": "Reseaux mobiles autonomes et essaims",
        "Statut": "Optionnel",
        "h_CM": 10,
        "h_TD": 10,
        "h_TP": 10,
        "Effectif": 10,
        "grCM": 1,
        "grTD": 1,
        "grTP": 1
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "ISI_02",
        "Intitule": "Conduite de projet",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 40,
        "h_TP": "",
        "Effectif": 70,
        "grCM": 1,
        "grTD": 3,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "INFO_01",
        "Intitule": "Administration des SE",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 23,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "INFO_02",
        "Intitule": "Analyse et decision en entreprise",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 70,
        "grCM": 1,
        "grTD": 3,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "INFO_04",
        "Intitule": "Architecture des SI",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 70,
        "grCM": "",
        "grTD": 3,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "INFO_06",
        "Intitule": "BD avancees",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 23,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "INFO_09",
        "Intitule": "IHM",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 23,
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "GEO_01",
        "Intitule": "Economie politique",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 60,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "GEO_05",
        "Intitule": "Marketing",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 60,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "SANTE_01",
        "Intitule": "Analyse des systèmes physiques",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 10,
        "grCM": 0,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "SANTE_04",
        "Intitule": "Notions de base en anatomie",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 10,
        "grCM": 0,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "TRANS_01",
        "Intitule": "Anglais",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 70,
        "grCM": 0,
        "grTD": 3,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "TRANS_02",
        "Intitule": "Communication",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 35,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "TRANS_03",
        "Intitule": "Decouverte de la recherche",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 70,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 1,
        "Ref": "TRANS_06",
        "Intitule": "Statistiques",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 35,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "ISI_01",
        "Intitule": "Architecture client_serveur",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 23,
        "grCM": 2,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "ISI_03",
        "Intitule": "Conduite du changement",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 23,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "ISI_04",
        "Intitule": "Contrôle qualite",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 23,
        "grCM": 0,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "ISI_05",
        "Intitule": "Ingenierie du logiciel",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 70,
        "grCM": 2,
        "grTD": 3,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "INFO_03",
        "Intitule": "Architecture Web des SI",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 70,
        "grCM": 2,
        "grTD": 3,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "INFO_05",
        "Intitule": "ASI mobiles 1",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 23,
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "INFO_07",
        "Intitule": "Bio informatique 1",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 12,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "INFO_08",
        "Intitule": "Conception avancee des SI",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 23,
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "GEO_02",
        "Intitule": "Gestion de production",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 30,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "GEO_06",
        "Intitule": "Marketing oriente Web",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 30,
        "grCM": 2,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "SANTE_02",
        "Intitule": "Droit de la sante et bioethique 1",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 12,
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "SANTE_03",
        "Intitule": "Instrumentation biomedicale 1",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 12,
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "TRANS_04",
        "Intitule": "Decouverte des laboratoires",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 29,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 2,
        "Ref": "TRANS_05",
        "Intitule": "Droit du travail",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 29,
        "grCM": 2,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "ISI_09",
        "Intitule": "Audit des SI",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "ISI_12",
        "Intitule": "Interoperabilite des SI (ETL)",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "ISI_14",
        "Intitule": "Conduite de projet agile",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 70,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_16",
        "Intitule": "Outils pour les systèmes decisionnels en entreprise",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_18",
        "Intitule": "Architecture des SI 2",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 70,
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_19",
        "Intitule": "ASI Mobile 2",
        "Statut": "Optionnel",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 23,
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_20",
        "Intitule": "Big data",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_21",
        "Intitule": "Bio-informatique 2",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 7,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_22",
        "Intitule": "Gestion de reseaux de capteurs biomedicaux",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 7,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_23",
        "Intitule": "IA",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 37,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_27",
        "Intitule": "Modelis. des pb en management et mkg",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_28",
        "Intitule": "Outils pour les donnees biomedicales",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 7,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_31",
        "Intitule": "Web Design",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 23,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "INFO_32",
        "Intitule": "Web x.0",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 23,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "GEO_09",
        "Intitule": "Theories des organisations",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 40,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 3,
        "Ref": "SANTE_06",
        "Intitule": "Instrumentation biomedicale 2",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 7,
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "ISI_11",
        "Intitule": "Progiciels de gestion integres",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "ISI_15",
        "Intitule": "Strategie et management des SI",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "ISI_16",
        "Intitule": "Ingenierie des SI en sante",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "ISI_17",
        "Intitule": "Management de la securite des SI",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 23,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "ISI_18",
        "Intitule": "Outils pour la Business intelligence",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "ISI_19",
        "Intitule": "Workflows",
        "Statut": "Optionnel",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 23,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "INFO_17",
        "Intitule": "Aide à la decision avancee",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "INFO_25",
        "Intitule": "Intelligence des systèmes biomedicaux",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 7,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "",
        "Semestre": 4,
        "Ref": "INFO_26",
        "Intitule": "Internet des objets (IoT)",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "INFO_29",
        "Intitule": "Recherche heuristique",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 20,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "GEO_08",
        "Intitule": "Strategie d'entreprise",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 60,
        "grCM": 1,
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "SANTE_05",
        "Intitule": "Electrophysiologie",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 7,
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "SANTE_07",
        "Intitule": "Telemedecine",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 7,
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "TRANS_08",
        "Intitule": "Anglais",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 67,
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "TRANS_09",
        "Intitule": "Data Science",
        "Statut": "Obligatoire",
        "h_CM": 8,
        "h_TD": 22,
        "h_TP": "",
        "Effectif": 35,
        "grCM": 1,
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": 4,
        "Ref": "TRANS_10",
        "Intitule": "Environnement socio-economique",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 67,
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": "AN",
        "Ref": "PRO_01",
        "Intitule": "Projet Professionnel",
        "Statut": "Referentiel",
        "h_CM": "",
        "h_TD": "",
        "h_TP": "",
        "Effectif": 70,
        "grCM": "",
        "grTD": "",
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": "AN",
        "Ref": "PRO_02",
        "Intitule": "Etude de cas creation d'entreprise",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 3,
        "grCM": "",
        "grTD": 1,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": "AN",
        "Ref": "PRO_03",
        "Intitule": "Etude de cas thematique",
        "Statut": "Obligatoire",
        "h_CM": "",
        "h_TD": 30,
        "h_TP": "",
        "Effectif": 67,
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": "AN",
        "Ref": "PRO_04",
        "Intitule": "Projet professionnel",
        "Statut": "Referentiel",
        "h_CM": "",
        "h_TD": "",
        "h_TP": "",
        "Effectif": 70,
        "grCM": "",
        "grTD": "",
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": "Foad",
        "Ref": "INFO_11",
        "Intitule": "Programmation orientee objet avancee",
        "Statut": "",
        "h_CM": 20,
        "h_TD": 5,
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": "Foad",
        "Ref": "ISI_07",
        "Intitule": "Methodes orientees objet d'analyse et de conception",
        "Statut": "",
        "h_CM": 20,
        "h_TD": 5,
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": "Foad",
        "Ref": "GEO_04",
        "Intitule": "Creation_Jeux d'entreprise",
        "Statut": "",
        "h_CM": "",
        "h_TD": 5,
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": "Foad",
        "Ref": "C306 - ISI_05",
        "Intitule": "Ingenierie du logiciel",
        "Statut": "",
        "h_CM": "",
        "h_TD": 20,
        "h_TP": "",
        "Effectif": 70,
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    },
    {
        "Formation": "Master Miage",
        "Semestre": "Foad",
        "Ref": "GEO_07",
        "Intitule": "eCommerce et technologies",
        "Statut": "",
        "h_CM": "",
        "h_TD": 60,
        "h_TP": "",
        "Effectif": "",
        "grCM": "",
        "grTD": 2,
        "grTP": ""
    }
]